### ISSUE TITLE
`Reservation` lacks `creation_time` and `update_time` attributes

### ISSUE THREAD

**Issue by hannes-ucsc** [googleapis/python-bigquery-reservation#150]
The reference documentation [claims](https://cloud.google.com/bigquery/docs/reference/reservations/rpc/google.cloud.bigquery.reservation.v1#reservation) that a `Reservation` response object has properties `creation_time` and `update_time` but there are no such attributes in the corresponding class in the Python API:

https://github.com/googleapis/python-bigquery-reservation/blob/27b256440b2565369c900cd4728e38676f82fcfe/google/cloud/bigquery_reservation_v1/types/reservation.py#L58

**Comment by tswast** [comment]
Fixed by https://github.com/googleapis/python-bigquery-reservation/pull/157/files#diff-a15ec31480883f2f7336a56f1a4c0662809d78086e0b4d9c4691027d845abb27R214
