### ISSUE TITLE
Location ID: EU is invalid.

### ISSUE THREAD

**Issue by volderette** [googleapis/python-bigquery-reservation#21]
I can only create reservations with location "US". Europe ("EU") doesn't seem to work:
Location ID: EU is invalid.

#### Environment details
  - `google-cloud-bigquery-reservation` version: 0.0.2

#### Steps to reproduce

  1. Set location to EU
  2. Call purchase_commitments()

#### Code example

```python
region = 'EU'
admin_project_id = 'admin_project'

def api_builder():
    res_api = ReservationServiceClient()
    parent_arg = "projects/{}/locations/{}".format(
        admin_project_id, region)
    return(res_api, parent_arg)

def purchase_commitment(slots=500):
    api = api_builder()
    res_api = api[0]
    parent_arg = api[1]
    commit_config = CapacityCommitment(plan='FLEX', slot_count=slots)
    commit = res_api.create_capacity_commitment(parent=parent_arg,
                                                capacity_commitment=commit_config)
    print(commit)
    return commit.name
```

**Comment by shollyman** [comment]
This doesn't appear to be the library, but the backend.  I've created https://issuetracker.google.com/issues/162759936 to track this with the backend team.

I'm going to close this issue, please follow the issue on the public issuetracker for updates.
