### ISSUE TITLE
Website out of date

### ISSUE THREAD

**Issue by darwinyip** [googleapis/python-bigquery-reservation#54]
The website needs to be updated https://googleapis.dev/python/bigqueryreservation/latest/changelog.html

**Comment by tswast** [comment]
I don't see any failed docs build jobs. Looks like the `prod:cloud-devrel/client-libraries/python/googleapis/python-bigquery-reservation/docs/docs` jobs never triggered.

**Comment by tswast** [comment]
Docs builds have been backfilled. Thank you for the report!
