### ISSUE TITLE
Provide sample codes on how to use methods

### ISSUE THREAD

**Issue by darwinyip** [googleapis/python-bigquery-reservation#56]
I'm reading through the documentation and it's very hard to navigate. There are no indications on how to use the classes.

For example, in `update_reservation`, what is the `update_mask`? Why is it needed? Why is there a `request` field? What is the difference between that and `Reservation`?

**Comment by tswast** [comment]
👍  Thank you for the request. I agree that sample code would be useful for this API.

`request` is a common field across all generated clients. It's used for creating API requests that need a more complex body than is possible with the other keyword arguments. For many APIs this is not particularly relevant, but it's needed in case the API surface changes in the future.

**Comment by KevinTydlacka** [comment]
I also have had some trouble working with this library for the same reason. The source is a bit cumbersome to wade through just to figure out how to make a simple request or two. I'd specifically love to see some samples around the BI Engine endpoints/methods.

**Comment by tswast** [comment]
I've created code samples in https://github.com/googleapis/python-bigquery-reservation/pull/144

Once they're running in our CI infrastructure, I'll try to get these added as examples in the docs.
