### ISSUE TITLE
Invalid Argument Error from python client

### ISSUE THREAD

**Issue by victorphamdeveloper** [googleapis/python-bigquery-reservation#61]
Hi, I'm trying to use the bigquery reservation python library to create the reservation. 
I was following the sample code from this page: https://cloud.google.com/blog/products/data-analytics/optimize-bigquery-costs-with-flex-slots. I think it was outdated since some of the classes name changed such as ReservationServiceClient instead of ReservationClient. 
Anyway, I was following that sample code and it throws an invalid argument error without telling me what exactly the invalid argument is. 
Could someone help shed a light, thank you!
#### Environment details

  - OS type and version
  - Python version: 3.7.8
  - pip version: 20.1.1
  - `google-cloud-bigquery-reservation` version: 1.0.0

#### Steps to reproduce

  1. Run the below code

#### Code example

```python
    res_client = ReservationServiceClient(
        credentials=hook._get_credentials()
    )
    parent = 'projects/{}/locations/{}'.format(project_id, location)

    commit_config = CapacityCommitment(plan='FLEX', slot_count=100)
    commit = res_client.create_capacity_commitment(
        parent=parent,
        capacity_commitment=commit_config
    )

    res_config = Reservation(slot_capacity=slots_count, ignore_idle_slots=False)
    res = res_client.create_reservation(
        parent=parent,
        reservation_id=f"reserve_{slots_count}_slots",
        reservation=res_config
    )

    assign_config = Assignment(
        job_type='QUERY',
        assignee='projects/{}'.format(project_id)
    )
    assign = res_client.create_assignment(parent=res.name, assignment=assign_config)
```

#### Stack trace
```
File "/usr/local/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Malformed reservation."
	debug_error_string = "{"created":"@1608178910.433859900","description":"Error received from peer ipv4:74.125.200.95:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"Malformed reservation.","grpc_status":3}"
```

Thanks!

**Comment by meredithslota** [comment]
Hi Victor! This is ... somewhat tricky, and I apologize. Here's our rationale: on Github and in the cloud.google.com docs, we intentionally don't provide code samples for _purchasing reservations_ (creating capacity commitments, etc.) because we don't want folks to copy-paste and accidentally spend money they didn't mean to spend. 

You can test out the API methods here: https://cloud.google.com/bigquery/docs/reference/reservations/rest/v1/projects.locations.reservations/create for creating reservations. We do also intend to add code samples for less ... financially-impactful actions such as listing reservations, etc. here: https://cloud.google.com/bigquery/docs/samples (https://cloud.google.com/bigquery/docs/samples/bigqueryreservation-quickstart) We have Go and Node.js code samples for that now, Python will be added soon.

**Comment by tswast** [comment]
Regarding class name changes, it's possible that code sample on the blog was written before we migrated to the microgenerator. Although I don't see an UPGRADING file like we have for other APIs https://github.com/googleapis/python-bigquery-storage/blob/master/UPGRADING.md

For constructing a valid request, I would suggest reviewing the following API documentation (generated from the backend protocol buffers)

https://googleapis.dev/python/bigqueryreservation/latest/bigquery_reservation_v1/types.html#google.cloud.bigquery_reservation_v1.types.CreateReservationRequest

https://googleapis.dev/python/bigqueryreservation/latest/bigquery_reservation_v1/types.html#google.cloud.bigquery_reservation_v1.types.Reservation

It appears you may be missing a `name` property on the `Reservation`.
